### ISSUE TITLE
Provide mean to verify parameters prior applying

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/tailor#104]
as we use tailor in a pretty complex environment - it'd be great to have a hook for a shell script? .. to be executed prior tailor update - to verify parameters (e.g. is the git repo url correct, or the nexus host) - and maybe even rewrite / change params ... 

@michaelsauter  - thoughts?

**Comment by michaelsauter** [comment]
Yes, we could have some "pre-status" hook, I guess it can be as simple as adding a flag that points to a shell script that is executed, and when that exits with non-zero, Tailor aborts. All the logic of the hook is outside Tailor scope though I'd say.

**Comment by michaelsauter** [comment]
See https://github.com/opendevstack/tailor/commit/cb4f1a6c600a6652d7640b18879395b59aa2e0e6.
