### ISSUE TITLE
Restructure documentation

### ISSUE THREAD

**Issue by rattermeyer** [opendevstack/tailor#108]
Create required antora component and modules, so documentation can be sourced from this repository.

Related to opendevstack/opendevstack.github.io#91

**Comment by michaelsauter** [comment]
@rattermeyer I would not do this right now. Tailor is versioned independently of ODS, and also documented differently. Right now all of Tailors doc is just the README which is already versioned, so I don't see a neeed for anything bigger. Once doc of Tailor is bigger, we can revisit using Antora.

**Comment by rattermeyer** [comment]
For antora it is ok, if it is versioned independently. Nevertheless tailor is an important part when working with ODS. Therefore, I would prefer to have it documented at the same place.

**Comment by michaelsauter** [comment]
Hmm, I just see it like a tool that one uses, like using the `oc` binary etc. I would not see it as part of the same docs ...

**Comment by rattermeyer** [comment]
I see your point. Have the impression, that users setting up OpenDevStack understand that oc is part of OpenShift, but would regard tailor as part of OpenDevStack.
But I am fine with leaving it as is and waiting for user feedback.
