### ISSUE TITLE
Tailor context

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/tailor#113]
Introduce the concept of a “Tailor context” (a context directory), and with that alter how template and param directories work. The goal is to enable Tailor run against multiple “sets of infrastructure definition”, such as present if you have multiple repos, each containing it’s own templates and possibly params. The use case for this comes from OpenDevStack.

The suggestion is to add a `--context-dir` flag, which can be repeated. By default, it is the working directory. Relative paths given in other flags will be resolved relative to each context.

The `--template-dir` defaults to the context dir. Right now, `--template-dir` is repeatable, but I think this is not required anymore with `--context-dir`. While not an exact replacement, having just one `--template-dir` will be much simpler and complicated use-cases can be covered via `--context-dir` in some way.

The `--param-dir` defaults to `${NAMESPACE}.env.d` in the context dir if that exists, otherwise the context dir itself. `--param-dir` is also repeatable by now, and the suggestion is to remove that feature as well, limiting to just one value.

The `param-file` defaults to `${NAMESPACE}.env` in the context dir if that exists. This flag can be repeated, and should continue to do so in the future.

The proposed changes simplify the rules significantly, and at the same time, make Tailor more powerful when working with spread out configuration.

**Comment by henrjk** [comment]
This makes sense to me. 

Does a context dir reference (typically) assume that they are located side by side on the file system?

Some more questions interspersed below:

> The suggestion is to add a `--context-dir` flag, which can be repeated. By default, it is the working directory. Relative paths given in other flags will be resolved relative to each context.

How are these other flags associated with a particular `--context-dir` ?

> The `--template-dir` ...

Could `--template-dir` be deprecated? 

> The `--param-dir` defaults to `${NAMESPACE}.env.d` in the context dir if that exists, otherwise the context dir itself. `--param-dir` is also repeatable by now, and the suggestion is to remove that feature as well, limiting to just one value.
> 
> The “param-file” defaults to “${NAMESPACE}.env” if that exists. This flag can be repeated, and should continue to do so in the future.

Is `env` meant literal or would it be substituted with the 'dev','test','uat' etc?

**Comment by michaelsauter** [comment]
The idea was that the layout of each context is assumed to be similar, therefore e.g. the `--template-dir` would be applied to each context. Example: `--context-dir="a" --context-dir="b" --template-dir="c"` would tell Tailor to look, when working on the first context, for templates in `a/c` and then, when working on the second context, in `b/c`. Does that make sense?

Yes, `env` is literal. `dev`, `test` etc. would fit into `$NAMESPACE`, so e.g. it would be something like `foo-dev.env` and `foo-test.env`.
