### ISSUE TITLE
install links do not work

### ISSUE THREAD

**Issue by henrjk** [opendevstack/tailor#134]
On github we have https://github.com/opendevstack/tailor/releases/download/v0.10.0/tailor-darwin-amd64
 
On the readme the reference uses underscores. The curl command does not fail but instead downloads `Not Found`.

**Comment by henrjk** [comment]
The readme also does not tell the user to use chmod +x at least for mac and linux?

**Comment by michaelsauter** [comment]
@henrjk Oh right. Fixed the links. The `chmod +x` is omitted - in my tests I did not have to do it. Did you need to do it? For me it seemed that Github preserved the executable flag of uploaded binaries ...

**Comment by michaelsauter** [comment]
Ok - I just added the instructions: https://github.com/opendevstack/tailor/commit/02f1336b5414da0b3703bc300d4eed3a2cbe828f.
