### ISSUE TITLE
upsert-only not recognized in Tailorfile

### ISSUE THREAD

**Issue by henrjk** [opendevstack/tailor#141]
tailor's readme currently says:

_Since specifying all params correctly can be daunting, and it isn't easy to share how Tailor should be invoked, Tailor supports setting CLI flags via a Tailorfile._

I concluded that this means all CLI flags and placed `upsert-only` in the Tailorfile.
However when running tailor update on the tailor file it still suggested and performed deletions.

I would have expected that instead tailor would work as if --upsert-only  had been used when invoked. 

The scenario is that not all resources are captured in the tailor resources and I only want to automatically update or create new resources.

**Comment by michaelsauter** [comment]
Did you specify `upsert-only` or `upsert-only true`? I think it needs to be the latter at the moment, even though I realise that might not be documented nor obvious. Please check if `upsert-only true` works.

IIRC that was done to distinguish flags from args (which do not have a value ...).

**Comment by henrjk** [comment]
I had `upsert-only` in my tailorfile. It works with 

```
upsert-only true
```

**Comment by michaelsauter** [comment]
Cool - noted in https://github.com/opendevstack/tailor/commit/d1481b18503aa8799044714085604c3b19fac347.
