### ISSUE TITLE
Think about merging of env

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/tailor#15]
Maybe it should be possible to merge multiple param files (e.g. having a global and a local config). Right now it is already possible to specify multiple param dirs, but the files inside are not merged yet.

FYI @clemensutschig

**Comment by michaelsauter** [comment]
Here's my current thinking:

If `--param-dir` is given multiple times, then we merge files with the same filename together, last one wins. E.g. `foo/bc.yml` defines `FOO=1` and `BAR=2`, and `baz/bc.yml` defines `BAR=3`. If Tailor is invoked with `--param-dir=foo --param-dir=baz` then the params `FOO=1` and `BAR=3` are used when the templates are processed.

Additionally, we should allow users to pass `--param-file` multiple times, again merging the files, last one wins. In this case, it does not matter if the files have the same filename or not.

Especially the second option opens the possibility to have e.g. a "global param file" and a more specific param file. However, this will probably require the user to specify `--ignore-unknown-parameters`, which is not ideal as you loose the "typo safeguard".

**Comment by clemensutschig** [comment]
Is there no way to find oit which params are needed in a Template...

**Comment by michaelsauter** [comment]
@clemensutschig Yes, we can do that. However, if we determine from the template which params we need, that is effectively the same as setting `--ignore-unknown-parameters`. 

To illustrate:
If you have an optional parameter in your template named `BITBUCKET_HOST`, and in your param file a param named `BBITBUCKET_HOST`, then by default `oc process`detects this typo. If you set `--ignore-unknwon-parameters` or just extract the params defined in the template you won't catch the error as easily.

I personally think the benefit of having a global param file outweigh the tradeoff to let go of this warning ... I just wanted to mention the tradeoff :)

Another option would be to import exactly the params you need from the global file, but I think that is unnecessarily complex UX wise ...
