### ISSUE TITLE
Comparing CronJob resources does not work

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/tailor#158]
Tailor uses `oc export` to get the cluster state. But that command produces very weird output for `CronJob` resources. There is no `kind` field ...

Even more interesting is that `oc get CronJob -oyaml` produces relatively normal output with a `kind` field of value `CronJob`.

Even more reason to switch from the deprecated `export` to `get` and do cleanup of fields/values ourselves ...

FYI @kiwo

**Comment by stefanlack** [comment]
Any news on this? I also stumpled over this bug.

**Comment by michaelsauter** [comment]
@stefanlack No news yet. The switch to `oc get` has potentially huge implications, so I want to go slowly, given this issue here is rather small.
