### ISSUE TITLE
Dealing with drift in immutable fields is difficult

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/tailor#162]
Experience shows that dealing with drift on immutable fields is difficult. Most common issues:

* PVCs were created via a different process, so e.g. `storageClassName` is not set, but the template defines it
* Size of PVC changes in the template, but existing PVCs should not be changed to avoid loosing data

Right now, Tailor prevents recreation by default, and has a `--allow-recreate` option to opt-in to recreation. I propose the following change:

* Deprecate `--allow-recreate`
* Add a new option, `--recreate-strategy`
  * defaults to `abort`, which means Tailor will stop to run (this matches current default behaviour of Tailor)
  * can be set to `allow`, which would have the same effect that `--allow-recreate` has right now
  * can be set to `avoid`, which shows the drift (visually it would be as if the fields were mutable) BUT it notes that the changes for the immutable fields will not be applied to the resource so that it does not have to be recreated. Doing a `tailor update --recreate-strategy=avoid` will result in patches of mutable fields applied, and patches to immutable fields ignored.

@gerardcl @henrjk Input on this?

**Comment by henrjk** [comment]
I like it, but why not have `avoid` be the default?

**Comment by michaelsauter** [comment]
Hmm, I think I chose `abort` as the default because:

1. the current behaviour is equal to the behaviour of `abort`
2. Tailor has by default only two states: when you run update, you are asked if you want to apply the updates. If you answer "no", you end up with the current state. If you answer "yes", you end up with the desired state. By default, you never end up with a "mixed" state, which is what `avoid` would give you ...

But I had some more thoughts on this over the weekend.

I realised that the `ignore-path` flag actually offers similar functionality than what I suggested with `avoid`. `ignore-path` basically "preserves current state" for given kind/resource/path.

Therefore, I have changed my mind ... and would now propose to do the following:

1. Rename `--ignore-path` to `--preserve`, making the effect a little clearer (as we are not ignoring the path e.g. during creation, we just preserve any current state there is).
2. Introduce a new `--preserve-immutable-fields`, which would be a shortcut to defining `--preserve` for every immutable field such as `/spec/host`. If this flag is present, recreation will not be triggered. If it is not present, recreation might be triggered which would lead Tailor to abort the action, and the user has to specify `--allow-recreate` as is the case right now.

One thing that came to my mind is that we have to check what Tailor does if the field is not present in the current state, but is present in the desired state. In this case it is important that the field is not being added when `--preserve-immutable-fields` is given as otherwise the resource would need to be recreated.

@henrjk Would love to hear what you think.

**Comment by henrjk** [comment]
@michaelsauter Beautiful! 

The last paragraph initially confused me, however it makes sense when it refers to fields. For example an explicit field for `storageClassName` which is not present in the current state ( I am not sure this is possible at all). Perhaps you can elaborate with an example on what case you were thinking off.

**Comment by michaelsauter** [comment]
@henrjk Cool that you like it!

It is indeed possible to have a resource without `storageClassName`. In that case, the cluster default is used. Now even if Tailor sets `storageClassName` to sth. that is the default, Tailor sees drift and wants to recreate the resource. 

Therefore I would say - if `storageClassName` is not defined in the current state, and `--preserve-immutable-fields` is given, it should stay that way. No drift, no change.

**Comment by henrjk** [comment]
Makes sense.

As a user I would be curious to understand what fields `--preserve-immutable-fields` covers in a concrete situation but also for reference. 

Would `--preserve-immutable-fields` be inactive by default?

**Comment by michaelsauter** [comment]
It would cover the fields which are defined as immutable - listed here: https://github.com/opendevstack/tailor/blob/master/pkg/openshift/item.go#L39-L50. Maybe we can expose that somehow in the help.

I think It should be inactive by default, because that makes the "mixed state" as described above an  intentional choice by the user. By default, there should only be either "current state" or "desired state" after your action.
