### ISSUE TITLE
use context dir with more than one tailor file

### ISSUE THREAD

**Issue by stefanlack** [opendevstack/tailor#167]
Requirement: I need to add a `context-dir` section to a given tailor file. 
The context dir should reference to a directory that contains more than one tailor file,

e.g. _ods-core/Tailorfile_:

`context-dir create-projects/templates/limits/core-resource-limits`

while the diretory _create-projects/templates/limits/core-resource-limits_ contains the following files:

*Tailorfile.apps*:
```
namespace cd
param-dir ../../../../../ods-configuration/core-resource-limits/apps
selector  configmap=core-resource-limits-apps

ignore-unknown-parameters true

cm
```

*Tailorfile.cd*:
```
namespace cd
param-dir ../../../../../ods-configuration/core-resource-limits/cd
selector  configmap=core-resource-limits-cd

ignore-unknown-parameters true

cm
```
*cm.yml*
_Template with object type *configMap*

If I execute `tailor update` inside  `ods-core`, I would expect that all tailor files in the specified context-dir are used.

Is  this possible with the current tailor version?

Maybe the syntax and semantic on _context-dir_ has to be extended, so that the tailor files can be specified, for example:

`context-dir create-projects/templates/limits/core-resource-limits --tailorFiles=Tailorfile.cd,Tailorfile.apps`

**Comment by michaelsauter** [comment]
Hmm this is not supported right now. Could you split the directory with the two tailorfiles so that you have two context dirs?

**Comment by stefanlack** [comment]
Yes, I do. As I expected this answer, I already changed the directory layout.

Toplevel Tailor file _ods-core/Tailorfile_:

```
context-dir create-projects/templates/limits/core-resource-limits/apps
context-dir create-projects/templates/limits/core-resource-limits/cd
```

One Tailorfile for _apps_, one for _cd_:
![image](https://user-images.githubusercontent.com/2901438/75691721-bd631280-5ca4-11ea-890a-686d18f12b2e.png)

Template _cm.yml_ referenced in each  sub-directory tailor file, e.g.

_apps/Tailorfile_:
```
namespace cd
param-dir ../../../../../../ods-configuration/limits/core-resource-limits/apps
template-dir ../
selector  configmap=core-resource-limits-apps

cm

```
_cd/Tailorfile_:
```
namespace cd
param-dir ../../../../../../ods-configuration/limits/core-resource-limits/cd
template-dir ../
selector  configmap=core-resource-limits-cd

cm

```

**Comment by michaelsauter** [comment]
Given #176, I'm closing this. Sorry for any inconvenience, but doing this cut before 1.0 is the right decision IMHO.
