### ISSUE TITLE
Remove context-dir support?

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/tailor#174]
I am suggesting to remove the `--context-dir` flag again.

Why was it introduced in the first place?
* To allow to compare state spread across multiple directories. Use case was to compare a complete ODS installation
* To allow to "clone" a project which resources are defined in multiple directories (component repositories)

I want to remove it now because:
* It adds significant complexity in the codebase
* It has some subtle issues and edge cases (contradicting/different options in global vs. local Tailorfile, nesting of context-dir definitions, ...)
* The first use case, to verify a complete ODS installation, can easily be achieved with other tools (shell script, Makefile, ...)
* The second use case, to clone a complete namespace, is currently being implemented (at least partially) in the MRO - which iterates over directories and executes Tailor in each
* We are still pre-1.0 so now is the best time

I just don't see enough justification for the feature to support it in the future.

Would like to hear your thoughts @oalyman @gerardcl @henrjk @stefanlack.

**Comment by henrjk** [comment]
So far we have not used the ``-context-dir`` flag. 

Regarding the second use case, how does the context dir help compared to scripting this?

**Comment by gerardcl** [comment]
hi @michaelsauter , I fully support this change:
- keep tailor simple
- comparison accross components/folders can done by using tailor from other context (e.g.: tools you already mentioned)
basically, it is more clean to manage it outside of tailor but using tailor, it gives much more flexibility!

**Comment by michaelsauter** [comment]
Thanks for feedback, will remove it.
