### ISSUE TITLE
Issues when env files do not have eol before eof

### ISSUE THREAD

**Issue by henrjk** [opendevstack/tailor#184]
We have multiple env files which are referenced in the Tailor file.
I just noticed when one file ended without a newline at the end that it confused tailor and the first entry of the next file becomes part of the value.

This is using tailor version 0.11.0

Example: 

Tailorfile

```
...

param-file file1.env
param-file file2.env
...
```

where `file1.env`
has as last entry:

```
DEVELOPMENT=0
```
without a newline at the end.

and `file2.env` starts with:

```
SOME_FLAG=on

```
then the value of `DEVELOPMENT` becomes `0SOME_FLAG=on` 

which leads to `SOME_FLAG` being reported as undefined.

**Comment by michaelsauter** [comment]
Ouch. Definitely sounds like a bug, thanks for reporting!
