### ISSUE TITLE
Tailor should support pre-actions

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/tailor#191]
A very Common requirement is to fill a variable needed during apply (eg host) based on dynamic information .. it would be great to have tailor support this..

**Comment by michaelsauter** [comment]
Related to #104.

Easiest way I see is to provide a way to specify some bash script that can be called, and that can:

- abort with exit code != 0
- add more params to Tailor - the easiest would probably be by exposing env variables that are prefixed with `TAILOR_PARAM_` or the like ?!

**Comment by clemensutschig** [comment]
Love it. The only piece needed is to put the params passed *to* tailor into
the env the script runs in.. that way one also knowsthe target namespace a
so on

Michael Sauter <notifications@github.com> schrieb am Di., 5. Mai 2020,
11:42:

**Comment by michaelsauter** [comment]
See https://github.com/opendevstack/tailor/commit/cb4f1a6c600a6652d7640b18879395b59aa2e0e6.
