### ISSUE TITLE
Jenkins does not come up on after initial tailor apply

### ISSUE THREAD

**Issue by georgfedermann** [opendevstack/tailor#201]
![image](https://user-images.githubusercontent.com/6222929/84933073-9c98be80-b0d5-11ea-9f6f-052be5d4e203.png)

**Comment by michaelsauter** [comment]
For posterity: we figured out that an annotation in a `ServiceAccount` resource might reference a `Route`, e.g. https://github.com/opendevstack/ods-core/blob/master/jenkins/ocp-config/deploy/jenkins-master.yml#L257. This might explain why the order was like this previously.
