### ISSUE TITLE
Take desired state from git repo?

### ISSUE THREAD

**Issue by renedupont** [opendevstack/tailor#210]
As far as I understand the readme, --template-dir, --param-dir and --param-file all assume a local location as value from which it retrieves it desired state to compare it to the cluster. I guess often these files are part of a git repo that is cloned to the local machine. 

It would be nice to have the possibility to let tailor work directly with the repo by e.g. supplying a --remote-url or --remote-template-dir param or something alike without requiring to have the files locally present.

**Comment by michaelsauter** [comment]
Generally I really like it 👍 I'm just a little hesitant of extending Tailor beyond what it really needs to do :)
