### ISSUE TITLE
tailor for Windows is identified as malware

### ISSUE THREAD

**Issue by serverhorror** [opendevstack/tailor#224]
Hello,

When trying to use tailor for local development on a Windows PC I see the following:

![tailor-win-v1 2 1](https://user-images.githubusercontent.com/36151/96111810-012c2480-0ee2-11eb-8435-5a477837b0b3.png)

Downloaded from:

* https://github.com/opendevstack/tailor/releases/download/v1.2.1/tailor-windows-amd64.exe

**Comment by michaelsauter** [comment]
😢 

Looks like we're hit by https://golang.org/doc/faq#virus. For more details, see https://github.com/golang/go/issues/18699.

The tl;dr is probably https://github.com/golang/go/issues/18699#issue-201458582:

> I suspect that the root cause for this is some malware actually does get written in Go, and then when the AV teams start looking for distinctive features of those binaries, they instead find features distinctive to Go instead of distinctive to the malware.

Signing (https://docs.microsoft.com/en-us/windows/win32/seccrypto/signtool) might help improve the score, but doesn't solve the actual problem. Not sure how to proceed from here, right now I don't see an easy option.

If you don't trust the binary, feel free to build from source using the provided `make` target.

**Comment by serverhorror** [comment]
I am in an enterprise setting and do not have control over what to trust and what not to trust, even at the highest level of trust developers are granted.

Asking central IT might take a while and doesn't quite help adoption.

I agree it's annoying for you having to solve this but this is what you have to deal with in enterprise environments (this seems solved with 1.2.2; so I'm closing this)

**Comment by michaelsauter** [comment]
If it is solved with 1.2.2, then this confirms above suspicion that it is basically an error of the virus/malware detection software, as nothing in the build process/distribution has changed. So there is actually nothing that an author of the Go binary could do other than making the malware detection software vendor aware of their "broken" detection logic.
