### ISSUE TITLE
Deployment Replicas as Tailor Param error

### ISSUE THREAD

**Issue by braisvq1996** [opendevstack/tailor#239]
If we try to set the replicas of the deployment config as a parameter in tailor we get an error ("STDIN": unrecognized type: int32)

Openshift: 3.11
OpenDevStack: 3.1
Tailor: 1.2.2

**Template File**
![image](https://user-images.githubusercontent.com/26645694/115223503-25c0bd80-a10c-11eb-918f-6f5208aefe51.png)

**Parameters File**
![image](https://user-images.githubusercontent.com/26645694/115223639-50ab1180-a10c-11eb-8305-b042bbce7a17.png)

**Tailor apply**
![image](https://user-images.githubusercontent.com/26645694/115222694-4b999280-a10b-11eb-99cc-e0e773dae603.png)

**Error**
> Updating dc/docker-plain-jss ... failed
Apply aborted: Error from server: error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps.openshift.io/v1\",\"kind\":\"DeploymentConfig\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"foo-docker-plain-jss\",\"template\":\"component-template\"},\"name\":\"docker-plain-jss\",\"namespace\":\"foo-dev\"},\"spec\":{\"replicas\":\"2\",\"revisionHistoryLimit\":10,\"selector\":{\"app\":\"foo-docker-plain-jss\",\"deploymentconfig\":\"docker-plain-jss\"},\"strategy\":{\"activeDeadlineSeconds\":21600,\"resources\":{},\"rollingParams\":{\"intervalSeconds\":1,\"maxSurge\":\"0%\",\"maxUnavailable\":\"100%\",\"timeoutSeconds\":600,\"updatePeriodSeconds\":1},\"type\":\"Rolling\"},\"template\":{\"metadata\":{\"labels\":{\"app\":\"foo-docker-plain-jss\",\"deploymentconfig\":\"docker-plain-jss\",\"env\":\"dev\"}},\"spec\":{\"containers\":[{\"image\":\"foo-dev/docker-plain-jss:latest\",\"imagePullPolicy\":\"IfNotPresent\",\"name\":\"docker-plain-jss\",\"ports\":[{\"containerPort\":8080,\"protocol\":\"TCP\"}],\"resources\":{\"limits\":{\"cpu\":\"100m\"},\"requests\":{\"cpu\":\"50m\"}},\"terminationMessagePath\":\"/dev/termination-log\",\"terminationMessagePolicy\":\"File\"}],\"dnsPolicy\":\"ClusterFirst\",\"restartPolicy\":\"Always\",\"schedulerName\":\"default-scheduler\",\"securityContext\":{},\"terminationGracePeriodSeconds\":30}},\"test\":false,\"triggers\":[{\"type\":\"ConfigChange\"},{\"imageChangeParams\":{\"automatic\":true,\"containerNames\":[\"docker-plain-jss\"],\"from\":{\"kind\":\"ImageStreamTag\",\"name\":\"docker-plain-jss:latest\",\"namespace\":\"foo-dev\"}},\"type\":\"ImageChange\"}]}}\n"}},"spec":{"replicas":"2","template":{"spec":{"$setElementOrder/containers":[{"name":"docker-plain-jss"}],"containers":[{"image":"foo-dev/docker-plain-jss:latest","name":"docker-plain-jss"}]}},"triggers":[{"type":"ConfigChange"},{"imageChangeParams":{"automatic":true,"containerNames":["docker-plain-jss"],"from":{"kind":"ImageStreamTag","name":"docker-plain-jss:latest","namespace":"foo-dev"}},"type":"ImageChange"}]}}
to:
Resource: "apps.openshift.io/v1, Resource=deploymentconfigs", GroupVersionKind: "apps.openshift.io/v1, Kind=DeploymentConfig"
Name: "docker-plain-jss", Namespace: "foo-dev"
Object: &{map["kind":"DeploymentConfig" "apiVersion":"apps.openshift.io/v1" "metadata":map["namespace":"foo-dev" "selfLink":"/apis/apps.openshift.io/v1/namespaces/foo-dev/deploymentconfigs/docker-plain-jss" "uid":"8fd67862-b0af-11ea-ad45-0050569e5437" "resourceVersion":"568926326" "generation":'\u0105' "creationTimestamp":"2020-06-17T15:31:06Z" "labels":map["app":"foo-docker-plain-jss" "template":"component-template"] "name":"docker-plain-jss" "annotations":map["kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"apps.openshift.io/v1\",\"kind\":\"DeploymentConfig\",\"metadata\":{\"annotations\":{},\"labels\":{\"app\":\"foo-docker-plain-jss\",\"template\":\"component-template\"},\"name\":\"docker-plain-jss\",\"namespace\":\"foo-dev\"},\"spec\":{\"replicas\":1,\"revisionHistoryLimit\":10,\"selector\":{\"app\":\"foo-docker-plain-jss\",\"deploymentconfig\":\"docker-plain-jss\"},\"strategy\":{\"activeDeadlineSeconds\":21600,\"resources\":{},\"rollingParams\":{\"intervalSeconds\":1,\"maxSurge\":\"0%\",\"maxUnavailable\":\"100%\",\"timeoutSeconds\":600,\"updatePeriodSeconds\":1},\"type\":\"Rolling\"},\"template\":{\"metadata\":{\"labels\":{\"app\":\"foo-docker-plain-jss\",\"deploymentconfig\":\"docker-plain-jss\",\"env\":\"dev\"}},\"spec\":{\"containers\":[{\"image\":\"foo-dev/docker-plain-jss:latest\",\"imagePullPolicy\":\"IfNotPresent\",\"name\":\"docker-plain-jss\",\"ports\":[{\"containerPort\":8080,\"protocol\":\"TCP\"}],\"resources\":{\"limits\":{\"cpu\":\"100m\"},\"requests\":{\"cpu\":\"50m\"}},\"terminationMessagePath\":\"/dev/termination-log\",\"terminationMessagePolicy\":\"File\"}],\"dnsPolicy\":\"ClusterFirst\",\"restartPolicy\":\"Always\",\"schedulerName\":\"default-scheduler\",\"securityContext\":{},\"terminationGracePeriodSeconds\":30}},\"test\":false,\"triggers\":[{\"type\":\"ConfigChange\"},{\"imageChangeParams\":{\"automatic\":true,\"containerNames\":[\"docker-plain-jss\"],\"from\":{\"kind\":\"ImageStreamTag\",\"name\":\"docker-plain-jss:latest\",\"namespace\":\"foo-dev\"}},\"type\":\"ImageChange\"}]}}\n"]] "spec":map["test":%!q(bool=false) "selector":map["app":"foo-docker-plain-jss" "deploymentconfig":"docker-plain-jss"] "template":map["metadata":map["creationTimestamp":<nil> "labels":map["app":"foo-docker-plain-jss" "deploymentconfig":"docker-plain-jss" "env":"dev"]] "spec":map["containers":[map["resources":map["limits":map["cpu":"100m"] "requests":map["cpu":"50m"]] "volumeMounts":[map["name":"sqlserver-vol" "mountPath":"/var/opt/mssql"]] "terminationMessagePath":"/dev/termination-log" "terminationMessagePolicy":"File" "imagePullPolicy":"IfNotPresent" "name":"docker-plain-jss" "image":"docker-registry.default.svc:5000/foo-dev/docker-plain-jss@sha256:18c34a8317809eeeaf20414bc6e7aa895d3e4c7967131dfbdf8309bffa40cb14" "ports":[map["containerPort":'\u1f90' "protocol":"TCP"]]]] "restartPolicy":"Always" "terminationGracePeriodSeconds":'\x1e' "dnsPolicy":"ClusterFirst" "securityContext":map[] "schedulerName":"default-scheduler" "volumes":[map["persistentVolumeClaim":map["claimName":"sqlserver-pvc"] "name":"sqlserver-vol"]]]"type":"Rolling"] "triggers":[map["type":"ConfigChange"] map["type":"ImageChange" "imageChangeParams":map["lastTriggeredImage":"docker-registry.default.svc:5000/foo-dev/docker-plain-jss@sha256:18c34a8317809eeeaf20414bc6e7aa895d3e4c7967131dfbdf8309bffa40cb14" "automatic":%!q(bool=true) "containerNames":["docker-plain-jss"] "from":map["kind":"ImageStreamTag" "namespace":"foo-dev" "name":"docker-plain-jss:latest"]]]] "replicas":'\x01' "revisionHistoryLimit":'\n'] "status":map["updatedReplicas":'\x01' "availableReplicas":'\x00' "unavailableReplicas":'\x01' "details":map["message":"image change" "causes":[map["type":"ImageChange" "imageTrigger":map["from":map["kind":"DockerImage" "name":"docker-registry.default.svc:5000/foo-dev/docker-plain-jss@sha256:18c34a8317809eeeaf20414bc6e7aa895d3e4c7967131dfbdf8309bffa40cb14"]]]]] "conditions":[map["lastUpdateTime":"2021-04-19T10:21:56Z" "lastTransitionTime":"2021-04-19T10:21:52Z" "reason":"NewReplicationControllerAvailable" "message":"replication controller \"docker-plain-jss-151\" successfully rolled out" "type":"Progressing" "status":"True"] map["message":"Deployment config does not have minimum availability." "type":"Available" "status":"False" "lastUpdateTime":"2021-04-19T10:22:17Z" "lastTransitionTime":"2021-04-19T10:22:17Z"]] "latestVersion":'\u0097' "observedGeneration":'\u0105' "replicas":'\x01']]}
for: "STDIN": unrecognized type: int32

@michaelsauter

**Comment by gerardcl** [comment]
hi @braisvq1996 , have you tried with `${{REPLICAS}}`, so to use double '{}' ? I believe that is, at least, one issue

**Comment by braisvq1996** [comment]
Thanks, that fixed it
I will close the issue
