### ISSUE TITLE
Tailor namespace replacement does not work as expected

### ISSUE THREAD

**Issue by pille321** [opendevstack/tailor#247]
command: tailor --verbose -n xyz-dev export route -l app=app
namespace: xyz-dev

**route**-xyz-dev.some.host.com will be replaced with **route**-${TAILOR_NAMESPACE}.some.host.com

xyz-dev-**route**.some.host.com will not be replaced

**Comment by michaelsauter** [comment]
Exporting has many quirks, there is just no way to get it "right". What you see is "intended behaviour", even if it is unfortunate in your case.

For more information, see https://github.com/opendevstack/tailor/commit/dc50cfcee179fe1eb8c318f11fb200b376a521c1 and https://github.com/opendevstack/tailor/commit/eb2c29d9fa8d00e6cd5a7b929eed46f3ae5f0ae0.
