### ISSUE TITLE
Fix resource creation order

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/tailor#41]
We need to create resources with no dependencies (e.g. PVC) before we create resources with dependencies (e.g. DC).

FYI @clemensutschig

**Comment by clemensutschig** [comment]
1.0 fix? If so Please assign to project

**Comment by michaelsauter** [comment]
I addressed a few issues on the road trip through the US, including this one. I'm going to open the PRs next week and then assign the rest of the issues to the project if it makes sense.

**Comment by clemensutschig** [comment]
@michaelsauter - sure
